name: php-revival-landing

services:
    app:
        image: php-revival-landing
        container_name: php-revival-landing
        build:
            context: .
            dockerfile: Composefile
        volumes:
            - .:/app:z
            - /app/node_modules
        ports:
            - 3000:3000
